### ISSUE TITLE
Multiple instance of babel-polyfill

### ISSUE THREAD

**Issue by robiiinos** [binance-chain/javascript-sdk#111]
Hello,

As per babel documentation, [polyfill shouldn't be used inside libraries but inside applications](https://babeljs.io/docs/en/babel-polyfill/)
This actually cause my Express app to crash when I try to implement BinanceCoin & BinanceChain into it

This is the error I am getting after downloading & implement the `javascript-sdk`.
``` Error: only one instance of babel-polyfill is allowed ```

Could you please consider moving away from `babel-polyfill` inside the SDK and migrate to `transform-runtime` ? as I can't get ride of it nor implement a check inside it to check if polyfill is already imported...

Reference: https://github.com/lebab/lebab/issues/249#issuecomment-318280870

Thanks

**Comment by notatestuser** [comment]
We have removed `babel-polyfill` and published this change in v2.11.0. Please have a look when you have a chance - thanks!

**Comment by robiiinos** [comment]
Got it working the day you closed the issue by modifying my local module; thanks for releasing a tag for this;
Everything's working now, ty !

**Comment by notatestuser** [comment]
Heads up: We will use `@babel/plugin-transform-runtime` as of v1.12.0 (#126).
