### ISSUE TITLE
Is there support for getting transaction history or updates using Javascript-SDK?

### ISSUE THREAD

**Issue by saarang1995** [binance-chain/javascript-sdk#116]
Hello,

I have implemented the **Javascript-SDK**, using which I was able to perform transfer, getAccount, getBalance etc. However, I couldn't find a way to receive transaction updates either via _REST API or Websockets_ in the **Javascript-SDK**. 

Can we use our own local node with the **Javascript-SDK**?

For example: I am creating the instance of the BnbClient using below line of code:
`const bnbClient = new BnbApiClient('https://testnet-dex.binance.org/');`

Regards,
Saarang Tiwari

**Comment by huangsuyu** [comment]
> Hello,
> 
> I have implemented the **Javascript-SDK**, using which I was able to perform transfer, getAccount, getBalance etc. However, I couldn't find a way to receive transaction updates either via _REST API or Websockets_ in the **Javascript-SDK**.
> 
> Can we use our own local node with the **Javascript-SDK**?
> 
> For example: I am creating the instance of the BnbClient using below line of code:
> `const bnbClient = new BnbApiClient('https://testnet-dex.binance.org/');`
> 
> Regards,
> Saarang Tiwari

hello,

the JS sdk doesn't support websocket. but it's support in https://github.com/binance-chain/go-sdk

You need to connect to HTTP/API: https://docs.binance.org/api-reference/dex-api/paths.html. 
so you cannot use your own node.

Cheers ^^
