### ISSUE TITLE
Enabling jdk for mainnet

### ISSUE THREAD

**Issue by sschiessl-bcp** [binance-chain/javascript-sdk#118]
I am connected to mainnet through dex.binance.org and I am converting private key to address, in that process I am getting a ''tbnb'' prefixed address. 

How can I switch that behavior?

**Comment by sschiessl-bcp** [comment]
Found following: 

Default behavior of `getAddressFromPublicKey` is switching to `tbnb`. Needs second argument to switch to `bnb`

**Comment by notatestuser** [comment]
Solved?

**Comment by sschiessl-bcp** [comment]
Yes, so far haven't found other need to differentiate between main and testnet

**Comment by rohitsahu21** [comment]
having same problem

const BnbApiClient = require('@binance-chain/javascript-sdk');

const api = ' https://dex.binance.org/';

const bncClient = new BnbApiClient(api);
bncClient.initChain();

const acc = bncClient.createAccountWithMneomnic();
console.log(acc);

but it create testnet wallet

**Comment by sschiessl-bcp** [comment]
Check if `createAccountWithMneomnic` also has second prefix argument

**Comment by sschiessl-bcp** [comment]
> Luke:
> Use client.chooseNetwork(“mainnet”)

**Comment by rohitsahu21** [comment]
Got it Thanks
