### ISSUE TITLE
Hierarchical Deterministic wallet

### ISSUE THREAD

**Issue by kennethhutw** [binance-chain/javascript-sdk#119]
Hello , 

        Does javascript-sdk support Hierarchical Deterministic wallet?

**Comment by huangsuyu** [comment]
> Hello ,
> 
> ```
>     Does javascript-sdk support Hierarchical Deterministic wallet?
> ```

hello, @kennethhutw 

Yes, it does.

**Comment by kennethhutw** [comment]
Hello @huangsuyu  , 
               How can I  generate multiple "child" private keys in a deterministic way?
