### ISSUE TITLE
check balance api 404

### ISSUE THREAD

**Issue by AlanGuo** [binance-chain/javascript-sdk#123]
https://testnet-dex.binance.org/api/v1/account/tbnb185tqzq3j6y7yep85lncaz9qeectjxqe5054cgn

![image](https://user-images.githubusercontent.com/727863/57344584-5eaf3400-717a-11e9-9e95-ae451c36d792.png)

**Comment by huangsuyu** [comment]
This is expected output since your address has no transaction history
