### ISSUE TITLE
getPrivateKeyFromMnemonic will only return account 0

### ISSUE THREAD

**Issue by bitcoinbrisbane** [binance-chain/javascript-sdk#128]
The function `getPrivateKeyFromMnemonic` https://github.com/binance-chain/javascript-sdk/blob/master/src/crypto/index.js#L279 will only ever return address_index 0, making it pretty useless.

`const HDPATH = "44'/714'/0'/0/0"`
`m / purpose' / coin_type' / account' / change / address_index`

- purpose = 44'
- coin_type = 714'
- account = 0'
- change = 0'
- address_index = 0

https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

**Comment by notatestuser** [comment]
Thanks
