### ISSUE TITLE
axios dependecy marked as vulnerable

### ISSUE THREAD

**Issue by emanuelet** [binance-chain/javascript-sdk#140]
![axios security alert](https://user-images.githubusercontent.com/8566422/58675395-bcecc280-8386-11e9-81ae-3336d4f45339.png)

axios <= 0.18 has been marked as vulnerable by github security. is it possilble to bump up the version?

**Comment by xzjcool** [comment]
Thanks a lot. will update

**Comment by emanuelet** [comment]
thanks. I have updated and it worked apparently on my local env. 
when I try to push it to my heroku environment I had a build issue with the `node-hid` so much so that I had to fix the version to `0.7.8` on my package.json.

I'm running Node 10.16.1 and npm 6.4.1

Not sure if it just related to something else in my environment but it was worth reporting

**Comment by notatestuser** [comment]
It has been updated. Thank you for the heads up!
