### ISSUE TITLE
 keypair.getPublic(...).encode is not a function

### ISSUE THREAD

**Issue by JineshJbspl0051** [binance-chain/javascript-sdk#144]
Hello 

I Just Implement BNB Implementation using javascript SDK but while generate public key got following error from sdk library please help out for this 

TypeError: keypair.getPublic(...).encode is not a function

**Comment by notatestuser** [comment]
Could you post the entire snippet of code here? I have no idea what `keypair` is supposed to represent here

**Comment by rajajwaliya** [comment]
check the packages of binance-chain/javascript-sdk were properly installed in node_module or not. i have same problem.
