### ISSUE TITLE
Source Identifier

### ISSUE THREAD

**Issue by jaggedsoft** [binance-chain/javascript-sdk#146]
How would we go about implementing Source Identifiers?

https://community.binance.org/t/call-for-submitting-your-source-identifier/4313
edit: this page was taken down :(

https://github.com/binance-chain/BEPs/pull/10

**Comment by huangsuyu** [comment]
> How would we go about implementing Source Identifiers?
> 
> https://community.binance.org/t/call-for-submitting-your-source-identifier/4313
> edit: this page was taken down :(
> 
> [binance-chain/BEPs#10](https://github.com/binance-chain/BEPs/pull/10)

You can read the post now >>>
https://community.binance.org/topic/110/call-for-submitting-your-source-identifier
