### ISSUE TITLE
createOrder throw exception

### ISSUE THREAD

**Issue by trumhemcut** [binance-chain/javascript-sdk#148]
While I call the createOrder, it throws the exception like this:

```'the order ID(CF16D7C101B40862CDB5DA498D4053F646B8EB7B-2) given did not match the expected one: `CF16D7C101B40862CDB5DA498D4053F646B8EB7B-7`'```

this.bnbClient.placeOrder(address, 'ONE-5F9_BNB', 1, 0.00070000, 1000, 1)

Could you please help take a look?

**Comment by notatestuser** [comment]
You were not providing the correct sequence. Please use `null` as the sequence argument.
