### ISSUE TITLE
API Example code - Call order dependance Bug: Example of Wallet to Wallet Transfer

### ISSUE THREAD

**Issue by intsol** [binance-chain/javascript-sdk#153]
The following lines need to be swapped for the example to successfully work on mainnet (it works on testnet by selecting the default "tbnb" address prefix)
- ```chooseNetwork``` sets this.addressPrefix, 
- ```setPrivateKey``` then uses this to set the address prefix string correctly.
 
```
bnbClient.setPrivateKey(privKey);
bnbClient.chooseNetwork("testnet"); // or this can be "mainnet"
```

Also, to find the client address, we can use either of the following methods.
The second method requires an address prefix string, however this is redundant, since it's already set up in the above calls internally in the bnbClient object.

```
const addressFrom = bnbClient.getClientKeyAddress();
const addressFrom = BnbApiClient.crypto.getAddressFromPrivateKey( privKey, "bnb");
```

**Comment by notatestuser** [comment]
Thank you! The example in the wiki has been updated with these suggestions. 👍
