### ISSUE TITLE
How Can We Decode send/transfer Transaction Data into hash via api??

### ISSUE THREAD

**Issue by rajajwaliya** [binance-chain/javascript-sdk#155]
hello i m trying to get original data from transaction hash via api. but i get amino encoded data. i am not understand how to get original data into transaction's hash.

request :- http://dataseed1.binance.org/tx?hash=0x7E47C88D812D738BFFD470D75DAD9B589C3C43BBD834E033905254EB394C81C7

response :- 
{
    "jsonrpc": "2.0",
    "id": "",
    "result": {
        "hash": "7E47C88D812D738BFFD470D75DAD9B589C3C43BBD834E033905254EB394C81C7",
        "height": "13666546",
        "index": 0,
        "tx_result": {
            "log": "Msg 0: ",
            "tags": [
                {
                    "key": "c2VuZGVy",
                    "value": "Ym5iMWo4dHBmOXI3bTdqNTVxbXJuend4aDZtY2VjZ2x3aHhtOTR2NHZ4"
                },
                {
                    "key": "cmVjaXBpZW50",
                    "value": "Ym5iMTRyc3VkcHEybHVqNmRnZDM1bHp4enRwcDUzaDRzZzNwZ2hmbnE5"
                },
                {
                    "key": "YWN0aW9u",
                    "value": "c2VuZA=="
                }
            ]
        },
        "tx": "1AHwYl3uCloqLIf6CikKFJHWFJR+36VKA2OYnGvreM4R91zbEhEKCE1JVEgtQzc2EID+n8TmWhIpChSo4caECv8lpqGxp8RhLCGkb1giIRIRCghNSVRILUM3NhCA/p/E5loScAom61rphyEDTCIY/zyKBx3tTzUuSIx7JAMqys/IgfOGkj1ly1Vk4a8SQPv4GdUIzE2OuEyDZTja0iL3aF6aMapfsaWvcqUoujzIOcAVZiUT5WxGM+YcyupDrBiGKc6IiZUNNcvsl2XA8j0Y7a0BICEgAQ=="
    }
}

**Comment by hiepnm** [comment]
Do you find the solution? Pls give your solution! Thanks

**Comment by rajajwaliya** [comment]
i just using https://testnet-dex.binance.org/api/v1/tx/4FBF179D1F32996BE9A0003F36E3384838877A2D31613415E2759E16AE3B433F?format=json
