### ISSUE TITLE
How to Get all the transaction of blockchain wia http api of BNB transfer ??

### ISSUE THREAD

**Issue by rajajwaliya** [binance-chain/javascript-sdk#156]
i m trying to get all the bnb block chain via http api. but i can't find any api which return all the bnb block chain transaction.

**Comment by mattabc9756** [comment]
same issue here , no one helping :( so sad,

**Comment by darren-liu** [comment]
all the blocks or all the txns in particular blocks?

there are ~2.5MM txns now and it doesn't stop increasing, apparently you can not get in one api.

If you want to get everyone of it, setting up your own full node may be your solution.

**Comment by notatestuser** [comment]
Please refer to this documentation for the HTTP endpoints:

If you use an Accelerated endpoint:
https://docs.binance.org/api-reference/api-server.html

If you run your own node:
https://docs.binance.org/api-reference/dex-api/paths.html
https://docs.binance.org/api-reference/node-rpc.html
