### ISSUE TITLE
How to generate an encoded public key?

### ISSUE THREAD

**Issue by testrain** [binance-chain/javascript-sdk#163]
E.g.:

```
$ tbnbcli keys add --recover --dry-run
> Enter your recovery seed phrase:
stumble chase victory bright iron plug laugh loud return recycle silk truck waste region hole spot crucial rifle detect tiny lecture wink airport buyer
NAME:	TYPE:	ADDRESS:						PUBKEY:
inmemorykey	local	tbnb1xjvftkyk0hhn4atmwwfye0kux8ktpfe5lcrxmx	bnbp1addwnpepq0grg7xh2d3c90flp7mus8e0u3zz0wzycfnevwmtag0426k5uydnjpsl69d
```

It seems using `crypto.getPublicKeyFromPrivateKey(crypto.getPrivateKeyFromMnemonic((mnemonics))` only outputs a hex string,  cannot generate an encoded PUBKEY like `bnbp1addwnpepq0grg7xh2d3c90flp7mus8e0u3zz0wzycfnevwmtag0426k5uydnjpsl69d`.

Does anyone have idea how to?  

Thanks!

**Comment by notatestuser** [comment]
The `bnb` prefixed string is known as an _address_, not a public key. Try using `crypto.getAddressFromPublicKey`.

**Comment by testrain** [comment]
Hey,

What I'm referring to is `bnbp1addwnpepq0grg7xh2d3c90flp7mus8e0u3zz0wzycfnevwmtag0426k5uydnjpsl69d` (PUBKEY), not the address `tbnb1xjvftkyk0hhn4atmwwfye0kux8ktpfe5lcrxmx`.  It seems current sdk api cannot generate the PUBKEY?

**Comment by notatestuser** [comment]
Ah, my bad. For that you can use the bech32 lib directly. check [this example](https://github.com/binance-chain/javascript-sdk/blob/46266762ae30f28814f85e11c4e2147f625c9140/src/crypto/index.js#L73)

**Comment by testrain** [comment]
Thank you Luke.

I've tried to use bech32 encode() and fromWords(), but it seems I'm still not able to get the same out as tbnbcli does. Can you please give some concrete example?

What I'm trying:

```
const bnbsdk = require('@binance-chain/javascript-sdk');
const bech32 = require('bech32');


const privateKey = bnbsdk.crypto.getPrivateKeyFromMnemonic(process.env.MNEMONIC);
const publicKey = bnbsdk.crypto.getPublicKeyFromPrivateKey(privateKey);
var words = bech32.toWords(Buffer.from(publicKey, 'hex'));
bech32.encode('bnbp', words, 200)
```

**Comment by testrain** [comment]
Hi @notatestuser Luke I still have trouble to get it generated PUBKEY. 

I'm guessing the bech32 encoding doesn't work directly on the EC public key, but the EC public key may get some compression / encoding / truncating before applying the bech32 encoding on it.

Can you please share more details or concrete examples? I'll be more than appreciated !

**Comment by notatestuser** [comment]
It would help to know what you're trying to do. We just support hexadecimal encoding in the SDK so if you're just trying to compare the outputs: you could decode the bech32 and compare the output bytes with the hex returned by `crypto.getPublicKeyFromPrivateKey`.

**Comment by testrain** [comment]
I'm just trying to derive everything from mnemonics: privateKey, publicKey, address.

The decoded result of PUBKEY actually doesn't match what's yielded from private key, so that's what confuses me and I'd like to figure out why:

mnemonic: `stumble chase victory bright iron plug laugh loud return recycle silk truck waste region hole spot crucial rifle detect tiny lecture wink airport buyer`

```
> const bnbsdk = require('@binance-chain/javascript-sdk');
> const bech32 = require('bech32')
> const privateKey = bnbsdk.crypto.getPrivateKeyFromMnemonic(process.env.MNEMONIC);
> const publicKey = bnbsdk.crypto.getPublicKeyFromPrivateKey(privateKey);
> publicKey
'04d03478d7536382bd3f0fb7c81f2fe44427b844c267963b6bea1f556ad4e11b39dee7ad18f5f2f95f86482c5d63ba834a999e7cf47fdbeaf72eebee0100c19a0f'
```

```
> Buffer.from(bech32.decode('bnbp1addwnpepq0grg7xh2d3c90flp7mus8e0u3zz0wzycfnevwmtag0426k5uydnjpsl69d').words, 'hex').toString('hex')
'1d0d0d0e13011901000f0803081e06170a0d1118050f091f011e1b1c1007190f1c1102020f0e0204180913190c0e1b0b1d080f150a1a16141c040d1312'
```

You could clearly see the bech32 decoded result differs from the EC public key. They even have different lengths. 

Can you help?

**Comment by notatestuser** [comment]
The bech32-encoded public key with the `bnbp1` prefix is encoded differently (more specifically, it's encoded with [Amino](https://github.com/binance-chain/bnc-go-amino)).

Here's a breakdown:
* The Amino type prefix for a Tendermint secp256k1 public key is 0xeb5ae987
* Then there is a length prefix that follows: 21 (which is 33 in decimal)
* Then you have your encoded public key: 03d03478d7536382bd3f0fb7c81f2fe44427b844c267963b6bea1f556ad4e11b39

Therefore, you can go both ways like this with the SDK:

Decode `bnbp` string to address:
```js
> aminoPrefixLen = 10
> pubkey = Buffer.from(bech32.fromWords(bech32.decode('bnbp1addwnpepq0grg7xh2d3c90flp7mus8e0u3zz0wzycfnevwmtag0426k5uydnjpsl69d').words), 'hex').toString('hex')
'eb5ae9872103d03478d7536382bd3f0fb7c81f2fe44427b844c267963b6bea1f556ad4e11b39'
> address = sdk.crypto.getAddressFromPublicKey(pubkey.substr(aminoPrefixLen))
'tbnb1xjvftkyk0hhn4atmwwfye0kux8ktpfe5lcrxmx'
```

Encode to `bnbp` string:
```js
> aminoPrefix = 'eb5ae98721'
> mnemonic = 'stumble chase victory bright iron plug laugh loud return recycle silk truck waste region hole spot crucial rifle detect tiny lecture wink airport buyer'
> pubkey = sdk.crypto.getPublicKeyFromPrivateKey(sdk.crypto.getPrivateKeyFromMnemonic(mnemonic))
'04d03478d7536382bd3f0fb7c81f2fe44427b844c267963b6bea1f556ad4e11b39dee7ad18f5f2f95f86482c5d63ba834a999e7cf47fdbeaf72eebee0100c19a0f'
> compressed = sdk.crypto.getPublicKey(pubkey).encodeCompressed('hex')
'03d03478d7536382bd3f0fb7c81f2fe44427b844c267963b6bea1f556ad4e11b39'
> bech32.encode('bnbp', bech32.toWords(Buffer.from(aminoPrefix + compressed, 'hex')))
'bnbp1addwnpepq0grg7xh2d3c90flp7mus8e0u3zz0wzycfnevwmtag0426k5uydnjpsl69d'
```
and you have arrived back at the encoded string you see printed by your `tbnbcli`.

The Amino prefix string `eb5ae98721` is a constant for any public key, so you can try this yourself with other mnemonics.

**Comment by testrain** [comment]
@notatestuser  Thanks very much for your detailed answer Luke! 

Does the Amino prefix also applies to other types of public keys, like consensus node public key ('bcap'), validator operator public key ('bvap'), etc. ?

**Comment by notatestuser** [comment]
Just based on the type/curve. Here is [a helpful table](https://github.com/tendermint/tendermint/blob/d419fffe18531317c28c29a292ad7d253f6cafdf/docs/spec/blockchain/encoding.md#public-key-cryptography).

**Comment by cbarraford** [comment]
hit this wall, and this issue was perfect. Thanks @notatestuser!
