### ISSUE TITLE
Potential bad behavior for client.getBalance() (proposal)

### ISSUE THREAD

**Issue by EnoRage** [binance-chain/javascript-sdk#167]
https://github.com/binance-chain/javascript-sdk/blob/master/src/utils/request.js#L40

For non existing account you will get error. However is it possible to check that account exists?
There is no any other option to check without an error. 

Maybe it is better to make function that will check that account exists inside of getBalance() function. If exists - then it will return result or network error?

P.S: Just some thoughts. We are building BNB extension like Metamask and got that an issue that we have errors for non existing accounts that is impossible to handle because of current behavior

**Comment by notatestuser** [comment]
Agree. We could make the function return an empty account instead

**Comment by guagualvcha** [comment]
@darren-liu 's concern is that if return with empty account instead, we can't trace/defend client that always query account that do not exist.

**Comment by notatestuser** [comment]
Could be caught and returned empty in the SDK


________________________________

**Comment by guagualvcha** [comment]
You mean still return 404, but sdk change it into an empty account?

**Comment by notatestuser** [comment]
Yes


________________________________
