### ISSUE TITLE
Ledger support broken for react

### ISSUE THREAD

**Issue by cbarraford** [binance-chain/javascript-sdk#172]
Making a note here about an issues where attempting to use ledger support...

```
const transport = await ledger.transports.node.create(timeout)
```

Results in an error....
```
Unhandled Rejection (TypeError): Cannot read property 'create' of null
```

`node` is `null` because it can't import `@ledgerhq/hw-transport-node-hid`. The reason why is because react mocks `fs`. See https://github.com/TooTallNate/node-bindings/issues/49

Not sure what the workaround would be here. Open to any suggestions. Thanks in advanced!

**Comment by notatestuser** [comment]
If you're building a web app the `u2f` transport might be what you want.

**Comment by cbarraford** [comment]
ahh, thanks for the tip.
