### ISSUE TITLE
"generateKeyStore(privateKeyHex, password)" is too slow in mobile 

### ISSUE THREAD

**Issue by Developmc** [binance-chain/javascript-sdk#173]
Test API "generateKeyStore(privateKeyHex, password)" in chrome , it takes 2-3 seconds;
However, it takes 20-30 seconds in Android mobile；takes 6-7seconds in iOS , Please check !

**Comment by notatestuser** [comment]
Keystores aren't so useful on mobile OS's because they typically do not have proper file management. What are you trying to do here?

**Comment by notatestuser** [comment]
We plan to change the keystore algorithm in favour of one that might work better on mobile devices.

**Comment by Developmc** [comment]
Thank you for your reply

**Comment by angelorc** [comment]
Any news on this? I have the same problem with NuxtJS, my browser stuck if I use generateKeyStore
