### ISSUE TITLE
Using multiSend with ledger

### ISSUE THREAD

**Issue by cbarraford** [binance-chain/javascript-sdk#174]
The api docs doesn't give a good example of how to use multisend with ledger. 

I gather you need to init the client with `useLedgerSigningDelegate`, but when i try to run `multiSend` after that i get the following error

```
Failed to sign with Ledger device: U2F TIMEOUT
```

Im not getting a prompt on my ledger to sign the request, so I wonder if theres a step i'm mising.
Thanks in advance! And thanks for this great js package!

**Comment by notatestuser** [comment]
Hi. Did you create the Ledger transport first? [Here is an example](https://github.com/binance-chain/javascript-sdk/wiki/API-Examples#ledger)

**Comment by cbarraford** [comment]
@notatestuser i believe so, here is my code for that part...
```
    // use the u2f transport
    const timeout = 10000
    const transport = await ledger.transports.u2f.create(timeout)
    const app = new ledger.app(transport)
```

**Comment by notatestuser** [comment]
Would you mind posting the full snippet of code?

I would take it through standard debugging steps:
* Try with something basic like `await app.getVersion()` to get the app version
* Try increasing the transport timeouts (2nd and 3rd args to the `app` constructor)
* Try a regular transfer. If that works your multi-send might just be too large

**Comment by cbarraford** [comment]
@notatestuser I did notice that `ledger.transports.u2f` would have a value of `false` by default, so I imported `@ledgerhq/hw-transport-u2f` manually and set u2f to the import.

here is a more complete snippet...

```
import { ledger, crypto } from '@binance-chain/javascript-sdk'
import Transport from '@ledgerhq/hw-transport-u2f'

ledger.transports.u2f = Transport

const ledgerConnect = async () => {

    // use the u2f transport
    const timeout = 50000
    const transport = await ledger.transports.u2f.create(timeout)
    const app = new ledger.app(transport)

    // do some things! (firmware app must be open now)

    // get version
    try {
      const version = await app.getVersion()
      console.log("version", version)
    } catch ({ message, statusCode }) {
      console.error("version error", message, statusCode)
    }

    // we can provide the hd path (app checks first two parts are same as below)
    const hdPath = [44, 714, 0, 0, 0]

    // get public key
    let pk
    try {
      pk = (await app.getPublicKey(hdPath)).pk
      // get address from pubkey
      const address = crypto.getAddressFromPublicKey(pk)
      console.log("address", address)

      context.setContext({
        "wallet": {
          "address": address,
          "ledger": app,
          "hdPath": hdPath,
        }
      })
}
```

1) I am able to get version number ok.
```
device_locked: false
error_message: "No errors"
major: 1
minor: 1
patch: 4
return_code: 36864
test_mode: false
```

2) I increased those timeout with no effect. Never prompted to sign on my ledger, and I get the error pretty fast (within a second or two).

3) Haven't tried a regular transfer yet, but i doubt the multisend is too large considering its just a coin going to two addresses.

**Comment by notatestuser** [comment]
Hmm, not quite sure what's happening here. Would you mind trying with a different tx - perhaps one that isn't using a string in place of a message object? Something like:
```json
{"account_number":"12","chain_id":"bnbchain","data":null,"memo":"smiley!☺","msgs":[{"id":"BA36F0FAD74D8F41045463E4774F328F4AF779E5-4","ordertype":2,"price":1612345678,"quantity":123456,"sender":"bnc1hgm0p7khfk85zpz5v0j8wnej3a90w7098fpxyh","side":1,"symbol":"NNB-338_BNB","timeinforce":3}],"sequence":"3","source":"1"}
```

**Comment by cbarraford** [comment]
will do. But I am stepping back from this development for a few weeks. Get back you in a month-ish. Thanks for the tip!

**Comment by cbarraford** [comment]
@notatestuser tried using your msg string, got the same error (as seen below). Will continue tinkering...

`TransportStatusError: Ledger device: UNKNOWN_ERROR (0x6984)`

**Comment by HaoyangLiu** [comment]
@cbarraford Did you have made it with other transaction types? Or your problems only happen on multisend transaction?

**Comment by cbarraford** [comment]
@HaoyangLiu i can't sign anything (not just multisend). Its seeming like a transport issue at this time and not relating to the code in this repo...

**Comment by HaoyangLiu** [comment]
Before sign the transaction, you need to call `ShowAddressSECP256K1`. Thus ledger can decide use which private key to sign.

**Comment by cbarraford** [comment]
@HaoyangLiu thanks, do you have example code somewhere? The example code wiki in this repo doesn't say anything about needing `ShowAddressSECP256K1`

**Comment by cbarraford** [comment]
heres my source code. https://gitlab.com/canyacoin/binancechain/binancetools/blob/ledger-support/src/components/pages/Wallet/Ledger.js#L18-L86

**Comment by HaoyangLiu** [comment]
Maybe you should call this before signing transaction: https://github.com/binance-chain/javascript-sdk/blob/4e32be6d263b869622e5384133a3a6db1b3ff9de/src/ledger/ledger-app.js#L507

**Comment by cbarraford** [comment]
@HaoyangLiu thanks, that solved the problem. I'll open a PR/etc to fix the wiki example. Thanks again.
