### ISSUE TITLE
Which interface gets the dynamic price of BNB

### ISSUE THREAD

**Issue by HelloRickey** [binance-chain/javascript-sdk#182]
Hi，I want to get the price of BNB，I use the  sdk of JavaScript.

**Comment by notatestuser** [comment]
There isn't anything to do this in the SDK for the time being. I would suggest pulling from [this API](https://dex.binance.org/api/v1/ticker/24hr?symbol=BNB_USDSB-1AC) if you'd like to get this data from the DEX (this fetches the ticker for the BNB/USDSB-1AC pair).

[API Documentation for the "ticker" endpoint](https://docs.binance.org/api-reference/dex-api/paths.html#apiv1ticker24hr)

**Comment by notatestuser** [comment]
Here is a pure SDK solution. Give this a try in the repl:

```js
const { rpc } = require('@binance-chain/javascript-sdk')
client = new rpc('https://dataseed1.binance.org:443')
client.getDepth('BNB_USDSB-1AC').then((...args) => { console.log('args', args) })
```

**Comment by HelloRickey** [comment]
> There isn't anything to do this in the SDK for the time being. I would suggest pulling from [this API](https://dex.binance.org/api/v1/ticker/24hr?symbol=BNB_USDSB-1AC) if you'd like to get this data from the DEX (this fetches the ticker for the BNB/USDSB-1AC pair).
> 
> [API Documentation for the "ticker" endpoint](https://docs.binance.org/api-reference/dex-api/paths.html#apiv1ticker24hr)

Thank you，friend，I know how to deal with it   ：）

**Comment by tazotodua** [comment]
@notatestuser  
from where to get those suffixes, i.e   "B-1AC": 
'BNB_USDS**B-1AC**'

how to find out those list or what does mean B, 1,A,C ?  
for example, if i want to get  ETH-USDT , or BTC-USDT, how find out the complete string for it?

**Comment by notatestuser** [comment]
Hi, you just have to query the tokens API for them and use the suffixes returned. They will not change.

Hope that helps.


________________________________

**Comment by tazotodua** [comment]
I've tried depending:
https://docs.binance.org/api-reference/api-server.html#apiv1tokens

this link:
https://api.binance.com/api/v1/tokens/

but getting error. Any hint how to get "tokens" ? 
thanks!

**Comment by notatestuser** [comment]
Try this:

https://dex.binance.org/api/v1/tokens?limit=1000


________________________________
