### ISSUE TITLE
tx parse error

### ISSUE THREAD

**Issue by saurabBajgain** [binance-chain/javascript-sdk#184]
Request URL: https://dex.binance.org/api/v1/broadcast?sync=true 
Response: 
code: 400
failed_tx_index: 0
message: "tx parse error"
success_tx_results: []

**function**:
 await this.client.initChain();
await this.client.placeOrder(address,symbol,side,price,quantity,sequence,timeinforce );
**parameters**: side=2,sequence=null,timeinforce=1,price=0.0031,quantity=21.75

**Comment by huangsuyu** [comment]
Please read the examples on how to set sequence: https://github.com/binance-chain/javascript-sdk/blob/4e32be6d263b869622e5384133a3a6db1b3ff9de/__tests__/client.test.js#L168

**Comment by magmel48** [comment]
same for me

**Comment by saurabBajgain** [comment]
> Please read the examples on how to set sequence:
> 
> https://github.com/binance-chain/javascript-sdk/blob/4e32be6d263b869622e5384133a3a6db1b3ff9de/__tests__/client.test.js#L168

Thankyou for your reply.
i have another problem, it says:-
code: 400
failed_tx_index: 0
message: "quantity(2175000000) is not rounded to lotSize(100000000)"
success_tx_results: []

where quantity is same as previous one i.e. quantity=21.75
what does it mean and how to deal with it while placing orders? 
thankyou

**Comment by huangsuyu** [comment]
> > Please read the examples on how to set sequence:
> > https://github.com/binance-chain/javascript-sdk/blob/4e32be6d263b869622e5384133a3a6db1b3ff9de/__tests__/client.test.js#L168
> 
> Thankyou for your reply.
> i have another problem, it says:-
> code: 400
> failed_tx_index: 0
> message: "quantity(2175000000) is not rounded to lotSize(100000000)"
> success_tx_results: []
> 
> where quantity is same as previous one i.e. quantity=21.75
> what does it mean and how to deal with it while placing orders?
> thankyou

The error message means that your order quantity needs to be multiple of 100000000

**Comment by saurabBajgain** [comment]
> > > Please read the examples on how to set sequence:
> > > https://github.com/binance-chain/javascript-sdk/blob/4e32be6d263b869622e5384133a3a6db1b3ff9de/__tests__/client.test.js#L168
> > 
> > 
> > Thankyou for your reply.
> > i have another problem, it says:-
> > code: 400
> > failed_tx_index: 0
> > message: "quantity(2175000000) is not rounded to lotSize(100000000)"
> > success_tx_results: []
> > where quantity is same as previous one i.e. quantity=21.75
> > what does it mean and how to deal with it while placing orders?
> > thankyou
> 
> The error message means that your order quantity needs to be multiple of 100000000


After i figure out this problem "quantity needs to be multiple of 100000000" again i reached to https://github.com/binance-chain/javascript-sdk/issues/184#issue-472220891  
same issue, where this time parameters are : side=2,sequence=6,timeinforce=1,price=0.002990795,quantity=20
sequence is generated as explained in https://github.com/binance-chain/javascript-sdk/blob/4e32be6d263b869622e5384133a3a6db1b3ff9de/__tests__/client.test.js#L16

two sell order was placed but now again its not working.
**error in console:-**
POST https://dex.binance.org/api/v1/broadcast?sync=true 400

error in HttpRequest#request Error: Request failed with status code 400
    at createError (createError.js:16)
    at settle (settle.js:17)
    at XMLHttpRequest.handleLoad [as __zone_symbol__ON_PROPERTYreadystatechange] (xhr.js:59)
    at XMLHttpRequest.wrapFn (zone.js:1166)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4620)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:192)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:499)
    at invokeTask (zone.js:1540) undefined


ERROR Error: Uncaught (in promise): Error: tx parse error
Error: tx parse error
    at request.js:69
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:392)
    at Object.onInvoke (core.js:4629)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:142)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4620)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:192)
    at resolvePromise (zone.js:824)
    at zone.js:746
    at rejected (main.js:3960)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:392)
    at Object.onInvoke (core.js:4629)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:142)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4620)


**Response in network:-**
code: 400
failed_tx_index: 0
message: "tx parse error"
success_tx_results: []

**Comment by huangsuyu** [comment]
@saurabBajgain 

how did you send your tx,

Here is an example: 
```
curl https://testnet-dex.binance.org/api/v1/broadcast -d "<your tx in hex>"  -H "content-type:text/plain”
```

**Comment by magmel48** [comment]
transaction is broadcasting right after calling placeOrder method of instance of BncClient

**Comment by saurabBajgain** [comment]
> @saurabBajgain
> 
> how did you send your tx,
> 
> Here is an example:
> 
> ```
> curl https://testnet-dex.binance.org/api/v1/broadcast -d "<your tx in hex>"  -H "content-type:text/plain”
> ```

as **@magmel48** said this is done by calling placeOrder method, isn't it? 
after calling **BncClient.pllaceOrder(..........)**; do we need to send tx manually as you said? if so can you please give me one example.. 

and same problem, sometime https://dex.binance.org/api/v1/broadcast?sync=true returns 200 with responce:-
code: 0
data: "{"order_id":"802ED92ECB2A9E73EA7BEFE4E6D0FA00D1A452AA-63"}"
hash: "7F677ABACCF6DDF2C4A185AAECCF9EF6D3D03348CEAB81828E5BB5829CE2983E"
log: "Msg 0: "
ok: true

and sometime returns 
code: 400
failed_tx_index: 0
message: "tx parse error"
success_tx_results: []
with same parameter values. 
Thankyou..

**Comment by huangsuyu** [comment]
@saurabBajgain 

You should increase the value of sequence in your transaction by one.

**Comment by saurabBajgain** [comment]
thankyou i got it.
for example:-in my case i am placing  sell order first and then buy order, after 15 second i want to cancel that previous sell order and buy orders, you mean here sequence for sell is 1, for buy 2 and so on, to cancel sell order sequence needs to be same as 1 (which is same for placing sell order) or it needs to be 3 (sell-1,buy-2,cancel sell-3,cancel buy-4). 
please correct me if i am wrong.

**Comment by saurabBajgain** [comment]
@huangsuyu 
successfully placed sale order :-
![sequence-101](https://user-images.githubusercontent.com/14971466/61948336-216c7c80-afda-11e9-8ea8-98df619d9162.jpg)
sucessfully placed buy order:-
![sequence-102](https://user-images.githubusercontent.com/14971466/61948343-26c9c700-afda-11e9-9124-2d77f88accea.jpg)
 but after reload browser and selecting same setting and on press of trade button:-
![photo_2019-07-26_19-16-34](https://user-images.githubusercontent.com/14971466/61948479-858f4080-afda-11e9-8d5c-6221995f0952.jpg)
 **what might be the reason behind this kind of situation?**,
 where sequence is generated as explained here   https://github.com/binance-chain/javascript-sdk/blob/4e32be6d263b869622e5384133a3a6db1b3ff9de/__tests__/client.test.js#L168  , price and quantity is same as successfully placed order.

**Comment by magmel48** [comment]
why it's closed if still not resolved?
