### ISSUE TITLE
Ledger wiki example missing "showAddress" requirement

### ISSUE THREAD

**Issue by cbarraford** [binance-chain/javascript-sdk#185]
related #174 

The [wiki page](https://github.com/binance-chain/javascript-sdk/wiki/API-Examples#ledger) that gives an example on using ledger is out of date and broken. Need to run `showAddress` before we can sign a message.

```
const address = await app.showAddress()
``` 

Please update the wiki with this please. I'd do it myself but not sure how I can submit a PR for the wiki.

**Comment by huangsuyu** [comment]
> related #174
> 
> The [wiki page](https://github.com/binance-chain/javascript-sdk/wiki/API-Examples#ledger) that gives an example on using ledger is out of date and broken. Need to run `showAddress` before we can sign a message.
> 
> ```
> const address = await app.showAddress()
> ```
> 
> Please update the wiki with this please. I'd do it myself but not sure how I can submit a PR for the wiki.

The wiki page is updated now.
