### ISSUE TITLE
Freeze unfreeze clients' token using token issuer's private key

### ISSUE THREAD

**Issue by amitsharma8891** [binance-chain/javascript-sdk#187]
Hi,

I wanted to implement end users' token using token issuer's private key. I found that to freeze token client can use their own private key but in my case, I want only token issuer can freeze and unfreeze the token.

Thanks

**Comment by huangsuyu** [comment]
Hello, @amitsharma8891 

Right now, Binance Chain users can only freeze tokens of their accounts. 

Token issuers can  use the [timelock](https://docs.binance.org/timelock.html) function.
