### ISSUE TITLE
Transaction demand

### ISSUE THREAD

**Issue by drunken005** [binance-chain/javascript-sdk#192]
Hello Binance chain team.

Can you separate the build Transaction from the Tansaction signature? or export the Transaction class at `/lib/index.js`.

Thanks!

---From [KOFO](https://kofo.io/#/en)

**Comment by notatestuser** [comment]
The Transaction class is now being exported in v2.15.0, published to npm today.

**Comment by drunken005** [comment]
> The Transaction class is now being exported in v2.15.0, published to npm today.

Thanks. I have rewritten the [binance SDK](https://www.npmjs.com/package/binance-utils) according to our business
