### ISSUE TITLE
How to connect own full node using javascript SDK

### ISSUE THREAD

**Issue by amitsharma8891** [binance-chain/javascript-sdk#195]
Hi,

I have started my own full node which is listening at port no 27147 also I started Api server listening at port 8080. How to use Javascript SDK to connect own full node. When I try to use SDK, it throws 404 error. 
e.g. http://127.0.0.1:8080/api/v1/node-info 

Can anyone tell me where am I doing wrong?

**Comment by xzjcool** [comment]
Can you show me your code?

**Comment by huangsuyu** [comment]
@amitsharma8891 
Hey, I think you are using the [HTTP API](https://docs.binance.org/api-reference/dex-api/paths.html) functions provided by accelerated nodes, which are not available in fullnode rpc. 

If you want to connect to your own node, please switch to [node rpc ](https://docs.binance.org/api-reference/node-rpc.html)functions.

**Comment by notatestuser** [comment]
I've added a working RPC example to the wiki [here](https://github.com/binance-chain/javascript-sdk/wiki/API-Examples#rpc-example-getaccount).
