### ISSUE TITLE
Context deadline exceeded

### ISSUE THREAD

**Issue by tphanson** [binance-chain/javascript-sdk#197]
First of all, It's hard to reproduce the error, but I think I should let you know.
I did a transaction on `mainnet` by `binance-chain/javascript-sdk`.
The response was an error which showed that `context deadline exceeded`, so I observed it as a failed transaction. However, It was indeed successfully executed `https://explorer.binance.org/tx/70A7D8105F1A32FFAF1647241BF07F45A7DCC71268B35885BB827CD65ED5D3C2`

Here is more details:
```
{ Error: context deadline exceeded
2019-08-14T14:27:46.215471677Z     at /usr/src/app/node_modules/@binance-chain/javascript-sdk/lib/utils/request.js:71:19
2019-08-14T14:27:46.215477675Z     at process._tickCallback (internal/process/next_tick.js:68:7) code: 500 }
```

If you ask me about firewall, or port-blocking, It will be not the causes. That transaction was failed randomly, that means there were some other successful transactions before and after this one.

**Comment by notatestuser** [comment]
Hi there. Could you tell us whether you used RPC or the Client class to broadcast the transaction?

**Comment by tphanson** [comment]
Sure
```
MAINNET: {
    id: 'Binance-Chain-Tigris',
    rpc: 'https://dex.binance.org'
  }
```

**Comment by xzjcool** [comment]
which method do you use to do the broadcast?

**Comment by tphanson** [comment]
> which method do you use to do the broadcast?

`bnbClient.api.transfer` this one

**Comment by xzjcool** [comment]
Good finding. That's an issue which has been fixed today. If happen again, please reopen this issue.
