### ISSUE TITLE
 message: 'invalid bech32 prefix. Expected bnb, Got tbnb'

### ISSUE THREAD

**Issue by mohammedaliarsh** [binance-chain/javascript-sdk#199]
After move to mainnet i am getting an error 

error in HttpRequest#request { Error: Request failed with status code 400
1|tokenSwap_Prod_Api  |     at createError (/home/javascript-sdk/node_modules/axios/lib/core/createError.js:16:15)
1|tokenSwap_Prod_Api  |     at settle (/home//node_modules/axios/lib/core/settle.js:18:12)
1|tokenSwap_Prod_Api  |     at IncomingMessage.handleStreamEnd (/homenode_modules/axios/lib/adapters/http.js:202:11)
1|tokenSwap_Prod_Api  |     at IncomingMessage.emit (events.js:194:15)
1|tokenSwap_Prod_Api  |     at endReadableNT (_stream_readable.js:1125:12)
1|tokenSwap_Prod_Api  |     at process._tickCallback (internal/process/next_tick.js:63:19)
1|tokenSwap_Prod_Api  |   config:
1|tokenSwap_Prod_Api  |    { adapter: [Function: httpAdapter],
1|tokenSwap_Prod_Api  |      transformRequest: { '0': [Function: transformRequest] },
1|tokenSwap_Prod_Api  |      transformResponse: { '0': [Function: transformResponse] },
1|tokenSwap_Prod_Api  |      timeout: 0,
1|tokenSwap_Prod_Api  |      xsrfCookieName: 'XSRF-TOKEN',
1|tokenSwap_Prod_Api  |      xsrfHeaderName: 'X-XSRF-TOKEN',
1|tokenSwap_Prod_Api  |      maxContentLength: -1,
1|tokenSwap_Prod_Api  |      validateStatus: [Function: validateStatus],
1|tokenSwap_Prod_Api  |      headers:
1|tokenSwap_Prod_Api  |       { Accept: 'application/json, text/plain, */*',
1|tokenSwap_Prod_Api  |         'User-Agent': 'axios/0.18.1' },
1|tokenSwap_Prod_Api  |      method: 'get',
1|tokenSwap_Prod_Api  |      baseURL: 'https://dex.binance.org/',
1|tokenSwap_Prod_Api  |      url:
1|tokenSwap_Prod_Api  |       'https://dex.binance.org/api/v1/account/tbnb...............................',
1|tokenSwap_Prod_Api  |      data: undefined },

 data:
1|tokenSwap_Prod_Api  |       { code: 400,
1|tokenSwap_Prod_Api  |         message: 'invalid bech32 prefix. Expected bnb, Got tbnb' } } } undefined
1|tokenSwap_Prod_Api  | (node:50103) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
1|tokenSwap_Prod_Api  |     at createError (/home/node_modules/axios/lib/core/createError.js:16:15)
1|tokenSwap_Prod_Api  |     at settle (/home/node_modules/axios/lib/core/settle.js:18:12)
1|tokenSwap_Prod_Api  |     at IncomingMessage.handleStreamEnd (/home/node_modules/axios/lib/adapters/http.js:202:11)
1|tokenSwap_Prod_Api  |     at IncomingMessage.emit (events.js:194:15)
1|tokenSwap_Prod_Api  |     at endReadableNT (_stream_readable.js:1125:12)
1|tokenSwap_Prod_Api  |     at process._tickCallback (internal/process/next_tick.js:63:19)

i am using  "@binance-chain/javascript-sdk": "^2.10.0",

**Comment by mohammedaliarsh** [comment]
and i cross check the address and all are of mainnet only they are starting with bnb prefix.. i am getting the above error while doing the transfer step..

**Comment by notatestuser** [comment]
Could you show us the key parts of the code you're using? I would guess that it's missing a line like this:
```js
client.chooseNetwork('mainnet')
```

**Comment by mohammedaliarsh** [comment]
Thanks for the reply..

**Comment by mohammedaliarsh** [comment]
thanks ..  that works for me...
