### ISSUE TITLE
 message: 'The receiver requires the memo contains only digits.',

### ISSUE THREAD

**Issue by mohammedaliarsh** [binance-chain/javascript-sdk#200]
when i am transferring on mainnet i am getting this error : 

 data:
 { code: 400,
 failed_tx_index: 0,
 message: 'The receiver requires the memo contains only digits.',
success_tx_results: [] } } }

**Comment by xzjcool** [comment]
are you transfer to Binance cex?

**Comment by mohammedaliarsh** [comment]
sorry i didn't get you.. i am transferring to a main net binance address

**Comment by xzjcool** [comment]
what i mean is do you transfer from your own wallet to Binance Cex address. because Binance Cex address will check the momo which should only be digits
