### ISSUE TITLE
signature verification failed 

### ISSUE THREAD

**Issue by 7metamorphosis** [binance-chain/javascript-sdk#206]
when use the transfer make the error   (signature verification failed )

 bnbClient.setPrivateKey(privateKey).then((res)=>{
                   bnbClient.transfer(address, adminAddress, 
                      money,symbol,remark,"").then((res)=>{ 

})
}

**Comment by notatestuser** [comment]
Could you provide more information, perhaps some code?  

What are each of the variables being used here?
