### ISSUE TITLE
Error when running an app with binance JavaScript SDK in docker container

### ISSUE THREAD

**Issue by rjkz808** [binance-chain/javascript-sdk#215]
When we run `yarn install` for our app (we use `loom-js`, which in order uses the binance chain JavaScript SDK) in regular ubuntu environment, everything works fine (even in WSL). But when we run `yarn install` in the docker container (which uses `node:10`) it can't build something named `node-hid`. This module is referenced inside the binance-chain JavaScript SDK. And without this module, nodejs fails in runtime because it can't resolve this module files

**Comment by eduardonunesp** [comment]
Sorry to comment on a closed issue, looks like you need to use the `npm i @binance-chain/javascript-sdk --no-optional` parameter to install `javascript-sdk` without use usb stuff

**Comment by emanuelet** [comment]
that unfortunately, doesn't solve the situation (at least for me). After attempting a lot of different things I ended up forking the repo (https://github.com/TravelbyBit/javascript-sdk/tree/remove_node_hid) and removing the dependency completely

**Comment by pshenmic** [comment]
Same error as above. Cannot run inside docker even if install with `--no-optional`
