### ISSUE TITLE
Get transaction with txid

### ISSUE THREAD

**Issue by Sotatek-CongNguyen** [binance-chain/javascript-sdk#222]
How I can get one transaction with transaction id using sdk? Tks

**Comment by kaiansaari** [comment]
It's not supported with the SDK currently, use the api instead: https://docs.binance.org/api-reference/dex-api/paths.html#apiv1txhash

**Comment by kaiansaari** [comment]
This is now supported. 

https://github.com/binance-chain/javascript-sdk/blob/master/docs/jsdoc.md#module_client.BncClient+getTx

**Comment by Sotatek-CongNguyen** [comment]
I think that it's better if function can pass option format as api

**Comment by kaiansaari** [comment]
Will add that in my next update if someone else hasn't. Thanks
