### ISSUE TITLE
getting error if address doesn't have balance

### ISSUE THREAD

**Issue by rstormsf** [binance-chain/javascript-sdk#231]
Example:

https://testnet-dex.binance.org/api/v1/account/tbnb139zdneq0zmfpwdnzgnmy4t3mkgr0pthu2pgzmu

returns an error

or if address has any history it does return JSON

**Comment by huangsuyu** [comment]
> Example:
> 
> https://testnet-dex.binance.org/api/v1/account/tbnb139zdneq0zmfpwdnzgnmy4t3mkgr0pthu2pgzmu
> 
> returns an error
> 
> or if address has any history it does return JSON

If a new address has no transaction history, then API cannot find anything related and it will return an error. It's expected
