### ISSUE TITLE
Warnings when using with nuxt.js

### ISSUE THREAD

**Issue by rstormsf** [binance-chain/javascript-sdk#232]
WARNING in ./node_modules/@binance-chain/javascript-sdk/lib/ledger/index.js 28:71-112
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@binance-chain/javascript-sdk/lib/index.js
 @ ./store/distribution.js
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

WARNING in ./node_modules/@binance-chain/javascript-sdk/lib/ledger/index.js 34:11-32
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@binance-chain/javascript-sdk/lib/index.js
 @ ./store/distribution.js
 @ ./.nuxt/store.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

**Comment by angelorc** [comment]
Yes, and the browser stuck when you use `crypto.generateKeyStore(privateKey, "1234567")`

**Comment by notatestuser** [comment]
Hi. Does this cause an actual problem or only produce warnings for now?

**Comment by rstormsf** [comment]
Just warnings

**Comment by angelorc** [comment]
Just warning
