### ISSUE TITLE
how to use getTx() function

### ISSUE THREAD

**Issue by shakeib98** [binance-chain/javascript-sdk#240]
I am unable to find a way to use getTx() function, and documentation examples are not helpful.

I am using it this way. 

    const bnbClient = new BnbApiClient(constants.BINANCE_API)
    await bnbClient.chooseNetwork("testnet")
    await bnbClient.setPrivateKey(constants.PRIVATE_KEY_BNB)
    await bnbClient.initChain()
    await.getTx('address')

But it is throwing error getTx() is not a function

**Comment by shakeib98** [comment]
Idk, but error was fixed after I installed the binance sdk again with --no-optional parameter.

**Comment by suraneti** [comment]
@shakeib98  you need to pass the hash value of a specific transaction instead of an address.

[reference.](https://github.com/binance-chain/javascript-sdk/wiki/API-Documentation#bncclientgettxhash--promise)
