### ISSUE TITLE
How to sign offline？

### ISSUE THREAD

**Issue by HebeBlock** [binance-chain/javascript-sdk#246]
Currently I am using: bnbClient.transfer (addressFrom, addressTo, amount, asset, message, sequence)

But I want to generate a hexadecimal, then sign it, and then send it out.

Is this okay?

**Comment by huangsuyu** [comment]
yes, that sounds alright. 

An example is here: https://github.com/binance-chain/javascript-sdk/blob/master/src/client/index.js#L303

you only need to gerentate signed tx offline, then broadcast it.

**Comment by xzjcool** [comment]
You can create our own Tx object https://github.com/binance-chain/javascript-sdk/blob/master/src/tx/index.js#L78 then sign it.

**Comment by HebeBlock** [comment]
@huangsuyu @xzjcool thank you
