### ISSUE TITLE
Support Non-english mnemonic for javascript-sdk

### ISSUE THREAD

**Issue by jtomtan** [binance-chain/javascript-sdk#247]
I am from Ownbit team. We have integrated BNB/BEP2 into Ownbit Wallet. There's a feedback for making this javascript-sdk support non-english mnemonics.

In the crypto module, change : 

if (!bip39.validateMnemonic(mnemonic)) {
    throw new Error("wrong mnemonic format")
  }

to : 

 if (!bip39.validateMnemonic(mnemonic, bip39.wordlists.egnlish)
        && !bip39.validateMnemonic(mnemonic, bip39.wordlists.chinese_simplified)
        && !bip39.validateMnemonic(mnemonic, bip39.wordlists.chinese_traditional)
        && !bip39.validateMnemonic(mnemonic, bip39.wordlists.korean)
        && !bip39.validateMnemonic(mnemonic, bip39.wordlists.french)
        && !bip39.validateMnemonic(mnemonic, bip39.wordlists.italian)
        && !bip39.validateMnemonic(mnemonic, bip39.wordlists.spanish)
        && !bip39.validateMnemonic(mnemonic, bip39.wordlists.japanese)) {
    throw new Error("wrong mnemonic format");
  }

Not all mnemonics are English. So this change should be a good improvement.  

BTW, we are trying to contact Binance team, to make a request to list Ownbit Wallet (ownbit.io) on the BNB wallets page. Who/Where should I contact? Or anywhere I can make a git issue for that?

**Comment by notatestuser** [comment]
Thanks for reporting this. Would you mind opening a pull request?

We can certainly get your wallet added to the docs site once we have a chance to try it out with the Binance Chain support.

**Comment by notatestuser** [comment]
The docs site repo is now public, feel free to send a PR: [binance-chain/docs-site](https://github.com/binance-chain/docs-site)

**Comment by jtomtan** [comment]
> The docs site repo is now public, feel free to send a PR: [binance-chain/docs-site](https://github.com/binance-chain/docs-site)

Thanks. Request pulled.

**Comment by jtomtan** [comment]
> Thanks for reporting this. Would you mind opening a pull request?
> 
> We can certainly get your wallet added to the docs site once we have a chance to try it out with the Binance Chain support.

Request pulled.
