### ISSUE TITLE
403 Forbidden access in binance chain sdk from Nodejs

### ISSUE THREAD

**Issue by umanggoyal89** [binance-chain/javascript-sdk#261]
We are using Binance Chain SDK to allow users to deposit and withdraw funds into Binance wallets. But most of the time we are getting 403 Forbidden access error. Previously it was working but only a few times we were getting this error but since last 1 or 2 weeks we are facing this issue. Is there any solution to this. Also we did not get any place to mention any API keys as we are not using the Dex APIs we are only using simple transfer and block information api end points.
This error is mainly coming when we try to access this API end point:
https://dex.binance.org/api/v1/transactions-in-block/'+blockNumber+'?format=json

however we are able to to use this endpoint:
https://dex.binance.org/api/v1/account/+bnbAddress
Any help is appreciated.

**Comment by xzjcool** [comment]
We have rate limit for 'https://dex.binance.org/api/v1/transactions-in-block/'+blockNumber+'?format=json', how do you use this api?

**Comment by xzjcool** [comment]
And we have increased rate limit.

**Comment by umanggoyal89** [comment]
> 
> 
> We have rate limit for 'https://dex.binance.org/api/v1/transactions-in-block/'+blockNumber+'?format=json', how do you use this api?

We are using this api to check if we have any new deposit for our wallet addresses. All other APIs are working fine but everytime we run this it throws forbidden access error. Is it possible that maybe our server IP address is blocked?

**Comment by xzjcool** [comment]
See, we have increased the rate limit. you can try again. btw which wallet?
