### ISSUE TITLE
How to generate new account and show getAccount?

### ISSUE THREAD

**Issue by RakaWA** [binance-chain/javascript-sdk#262]
I see references like here https://github.com/binance-chain/javascript-sdk/wiki/API . But it didn't work when viewing account info (getAccount) like this:
```
const BnbApiClient = require('@binance-chain/javascript-sdk');
const api = 'https://testnet-dex.binance.org/'; /// api string
const client = new BnbApiClient(api);
client.chooseNetwork("testnet");
client.initChain();
const gen = client.createAccountWithMneomnic();
const address = gen.address;
const mnemonic = gen.mnemonic;
const privateKey = gen.privateKey;
client.getAccount(address).then(result => {
    console.log(result);
});
```
The code above output is "null". Is there something wrong with that? please help me. Thank you

**Comment by xzjcool** [comment]
Once you create a new address, you have to transfer assets first, then you can see the account info
