### ISSUE TITLE
Error parsing transaction from getTxByHash

### ISSUE THREAD

**Issue by huangsuyu** [binance-chain/javascript-sdk#267]
对于交易hash  FC3F58350903DD80632F3E6F88EC28FEEC248636E6E666AC6DEDF92F31FC4E06

需求：需要使用rpc接口来获取tx，能解析出from,to,交易币种，数量，手续费和memo

如使用加速节点api

https://testnet-dex.binance.org/api/v1/tx/FC3F58350903DD80632F3E6F88EC28FEEC248636E6E666AC6DEDF92F31FC4E06?format=json

而使用nodejs sdk的 getTxByHash 结果是这样的

`

{
  "hash": "FC3F58350903DD80632F3E6F88EC28FEEC248636E6E666AC6DEDF92F31FC4E06",
  "height": "90563483",
  "index": 0,
  "tx_result": {
    "log": "Msg 0: ",
    "events": [
      {
        "attributes": [
          {
            "key": "sender",
            "value": "tbnb1hdl6vs547xyhlmly04egml4c6lepm57w0c6gel"
          },
          {
            "key": "recipient",
            "value": "tbnb1q62eesqznkmsh48cgljhh7cvqs0p2nemxthera"
          },
          {
            "key": "action",
            "value": "send"
          }
        ]
      }
    ]
  },
  "tx": {
    "msg": [
      {
        "inputs": [
          {
            "address": {
              "type": "Buffer",
              "data": [
                187,
                127,
                166,
                66,
                149,
                241,
                137,
                127,
                239,
                228,
                125,
                114,
                141,
                254,
                184,
                215,
                242,
                29,
                211,
                206
              ]
            },
            "coins": [
              {
                "denom": "BNB",
                "amount": 2948140
              },
              {
                "denom": "\u0006���\u0002��\u000b��G�{�\f\u0004\u001e\u0015O;",
                "amount": 0
              }
            ]
          }
        ],
        "outpus": [
          {
            "address": null,
            "coins": [
              {
                "denom": "",
                "amount": 0
              }
            ]
          }
        ],
        "aminoPrefix": "2A2C87FA"
      }
    ],
    "signatures": [
      {
        "pub_key": null,
        "signature": null,
        "account_number": 0,
        "sequence": 0
      }
    ],
    "memo": "",
    "source": 0,
    "data": "",
    "aminoPrefix": "F0625DEE"
  }
}

`

**Comment by woyoutlz** [comment]
相同的问题，解析出 {
"denom": "\u0006���\u0002��\u000b��G�{�\f\u0004\u001e\u0015O;",
"amount": 0
}

**Comment by woyoutlz** [comment]
乱码部分不知道是什么
