### ISSUE TITLE
Module '"crypto"' has no default export.

### ISSUE THREAD

**Issue by stuartwk** [binance-chain/javascript-sdk#292]
When trying to use this in Angular 10, when building I get the error...

```
ERROR in node_modules/@binance-chain/javascript-sdk/lib/declarations.d.ts:15:12 - error TS1192: Module '"crypto"' has no default export.

15     import _crypto from "crypto";
```

Changing line 15 to `import * as _crypto from "crypto";` resolves the issue for me.

**Comment by stuartkuentzel** [comment]
Any update on this? It's preventing Angular projects from using this library.
