### ISSUE TITLE
Multi-address support (variable HD path)

### ISSUE THREAD

**Issue by notatestuser** [binance-chain/javascript-sdk#41]
The HD path used is [hard-coded](https://github.com/binance-chain/javascript-sdk/blob/e218e3fbd8171b6ca0aff998822c9e7df89a5a48/src/crypto/index.js#L24) to `44'/714'/0'/0/0`. This change would allow it to be supplied as an arg and changed as needed to get multiple addresses from the same seed.

**Comment by bitcoinbrisbane** [comment]
@notatestuser I guess we close this one now?
