### ISSUE TITLE
Inconsistency with documentation and API

### ISSUE THREAD

**Issue by zzq229** [binance-chain/javascript-sdk#61]
Hi Binance Chain team, when I am trying Binance js sdk I found that some methods in API Documentation are not implemented (eg. getClientKeyAddress()) and some methods (eg. initChain(), setPrivateKey()) are not recorded in API Documentation.

**Comment by notatestuser** [comment]
Thanks, `getClientKeyAddress` will be in the next release if you are using the npm version. Some undocumented methods are missing JSDoc comments at the moment - these will be added shortly!
