### ISSUE TITLE
PlaceOrder worked yesterday. Not today. No code changes. What gives?

### ISSUE THREAD

**Issue by sandybradley** [binance-chain/javascript-sdk#70]
C:\Users\Alexander Bradley\Documents\binance\comp>node test.js

error in HttpRequest#request { Error: Request failed with status code 401
    at createError (C:\Users\Alexander Bradley\Documents\binance\comp\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Alexander Bradley\Documents\binance\comp\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Alexander Bradley\Documents\binance\comp\node_modules\axios\lib\adapters\http.js:201:11)
    at IncomingMessage.emit (events.js:193:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'text/plain',
        'User-Agent': 'axios/0.18.0',
        'Content-Length': 444 },
     method: 'post',
     baseURL: 'https://testnet-dex.binance.org/',
     url: 'https://testnet-dex.binance.org/api/v1/broadcast?sync=true',
     data:
      'dc01f0625dee0a64ce6dc0430a14c6c68e35e190e8f1177594402bae86edc1ddf313122a433643363845333545313930453846313137373539343430324241453836454443314444463331332d311a0d424e425f4254432e422d3931382002280230f0e9163880c2d72f4003126e0a26eb5ae9872102223ce545a3af8adaddb30858106abcf9ae4e78975cb78bca65caf198a90c7f651240631dad796fdaf725940c21f39ad6d907b9bc3ecb72d6c109279ce736438f8cce4bf041cbd6a0d8b020c6222e3fab74dd47f1bdbef1cd654e81c18f2844bbecd918b1f2062001' },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'testnet-dex.binance.org',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'testnet-dex.binance.org',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 67,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'testnet-dex.binance.org',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'testnet-dex.binance.org',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 67,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _header:
      'POST /api/v1/broadcast?sync=true HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: text/plain\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 444\r\nHost: testnet-dex.binance.org\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/api/v1/broadcast?sync=true',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 401,
        statusMessage: 'Unauthorized',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl: 'https://testnet-dex.binance.org/api/v1/broadcast?sync=true',
        redirects: [] },
     aborted: false,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 444,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'https://testnet-dex.binance.org/api/v1/broadcast?sync=true' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'content-type': [Array],
        'user-agent': [Array],
        'content-length': [Array],
        host: [Array] } },
  response:
   { status: 401,
     statusText: 'Unauthorized',
     headers:
      { 'content-type': 'application/json',
        'content-length': '122',
        connection: 'close',
        date: 'Fri, 08 Mar 2019 11:41:12 GMT',
        'x-ratelimit-limit-second': '5',
        'x-ratelimit-remaining-second': '4',
        'x-ratelimit-limit-minute': '300',
        'x-ratelimit-remaining-minute': '299',
        'access-control-allow-origin': '*',
        'cache-control': 'no-cache, no-store, must-revalidate',
        'strict-transport-security': 'max-age=31536000',
        'x-kong-upstream-latency': '2',
        'x-kong-proxy-latency': '1',
        via:
         'kong/0.14.1, 1.1 b140ebac2d560cbb139c002477015c3a.cloudfront.net (CloudFront)',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '1; mode=block',
        'x-content-type-options': 'nosniff',
        'referrer-policy': 'origin-when-cross-origin',
        'x-cache': 'Error from cloudfront',
        'x-amz-cf-id': 'xkMPzTYDb11WVcNiRUd4oyQtxKio8yQRyMU6XOyRjsF6qQahPE9F5g==' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'post',
        baseURL: 'https://testnet-dex.binance.org/',
        url: 'https://testnet-dex.binance.org/api/v1/broadcast?sync=true',
        data:
         'dc01f0625dee0a64ce6dc0430a14c6c68e35e190e8f1177594402bae86edc1ddf313122a433643363845333545313930453846313137373539343430324241453836454443314444463331332d311a0d424e425f4254432e422d3931382002280230f0e9163880c2d72f4003126e0a26eb5ae9872102223ce545a3af8adaddb30858106abcf9ae4e78975cb78bca65caf198a90c7f651240631dad796fdaf725940c21f39ad6d907b9bc3ecb72d6c109279ce736438f8cce4bf041cbd6a0d8b020c6222e3fab74dd47f1bdbef1cd654e81c18f2844bbecd918b1f2062001' },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'POST /api/v1/broadcast?sync=true HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: text/plain\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 444\r\nHost: testnet-dex.binance.org\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/api/v1/broadcast?sync=true',
        _ended: true,
        res: [IncomingMessage],
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data:
      { code: 65540,
        message:
         '{"codespace":1,"code":4,"abci_code":65540,"message":"signature verification failed"}' } } }
error { Error: signature verification failed
    at C:\Users\Alexander Bradley\Documents\binance\comp\node_modules\@binance-chain\javascript-sdk\lib\utils\request.js:71:21
    at process.internalTickCallback (internal/process/next_tick.js:77:7) code: 4, abci_code: 65540 }

**Comment by notatestuser** [comment]
We are not seeing any problems here. Please provide your test case code (remove any private keys/seed phrases).

Closing until you can get back to us.
