### ISSUE TITLE
placeOrder error

### ISSUE THREAD

**Issue by fangfan525** [binance-chain/javascript-sdk#86]
testing environment：https://testnet-dex.binance.org
Why do you report this error without the chain ID parameter
Error: chain id should not be null

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or
array-like object.
My first parameter is the string. Why did I report this error?

**Comment by notatestuser** [comment]
Please reply with an example of the code you are trying to use. Remember that the client must be initialized before use: `await client.initChain()` to populate the internal chain ID.
