### ISSUE TITLE
Use sha3 for keystore macs

### ISSUE THREAD

**Issue by notatestuser** [binance-chain/javascript-sdk#92]
To remain compatible with the [Web3 Secret Storage Definition](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition)

**Comment by xzjcool** [comment]
https://github.com/ethereum/eth2.0-specs/issues/612. we can keep sha256

**Comment by notatestuser** [comment]
That discussion is not about secret storage (keystore).

**Comment by xzjcool** [comment]
i know that. but the point is the sha256 is faster than sha3
