### ISSUE TITLE
Serialization for Transaction

### ISSUE THREAD

**Issue by sschiessl-bcp** [binance-chain/javascript-sdk#99]
To allow sophisticated use of the Signing (see [here](https://github.com/binance-chain/javascript-sdk/blob/1464960b2c502e4e3e62357f8db4a3264632539a/src/client/index.js#L29)) and Broadcast delegate, serialization and de-serialization of the Transaction class and the `signMsg` must be possible at all states of it (unsigned and signed).

I would propose to add a `toJSON` and `static fromJSON` method that will allow usage of JSON stringify and JSON parse.

**Comment by notatestuser** [comment]
I agree that a `toJSON` and `fromJSON` might be helpful for turning a sign doc object back into a Transaction, but did not really understand what you meant by "must be possible at all states of it" - could you elaborate?

**Comment by sschiessl-bcp** [comment]
Apologies, that comment came from looking at [this here](https://github.com/binance-chain/javascript-sdk/blob/4cad60d29b7a79817bfa911487239b74dfd935cc/src/tx/index.js#L120) which can only be serialized if signed.

This issue is the last blocker (I think :) ) for full feature support of our soon-to-be submitted signing service. Currently we support transfer and the order operations.

**Comment by notatestuser** [comment]
I see, so you would like to have access to the `StdTx` structure before having attached a signature?

**Comment by sschiessl-bcp** [comment]
My goal is to be able to do that:
```
export const ExternalSigningDelegate = async function(tx, signMsg) {
  let serializedSignedTransaction = await getItSignedSomewhere(
      JSON.stringify(serializedTx.toJSON()),
      JSON.stringify(signMsg.toJSON())
  );
  return Transaction.fromJSON(serializedSignedTransaction);
}
```

**Comment by sschiessl-bcp** [comment]
The same should be able to be done with the `BroadcastingDelegate`, that is what I meant with state-independent.

**Comment by sschiessl-bcp** [comment]
What are the chances this gets supported? :ship:

**Comment by notatestuser** [comment]
We would definitely consider a PR for this, it should not be too complex to add but we have a roadmap for the SDK

**Comment by sschiessl-bcp** [comment]
Was this closed because it is now fixed?
